version: '3'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - tris-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - tris-network
    depends_on:
      - server

networks:
  tris-network:
    driver: bridge